import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
  <header className="border-b border-black/10 bg-white">
    <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
      <a href="/" className="text-sm font-semibold tracking-wide">
        747 GARAGE
      </a>

      <nav className="hidden gap-6 text-sm text-black/70 md:flex">
        <a className="hover:text-black" href="/vehicles">Veículos</a>
        <a className="hover:text-black" href="/parts">Peças</a>
        <a className="hover:text-black" href="/projects">Projetos</a>
        <a className="hover:text-black" href="/services">Serviços</a>
        <a className="hover:text-black" href="/schedule">Agendamento</a>
        <a className="hover:text-black" href="/about">Sobre</a>
        <a className="hover:text-black" href="/contact">Contato</a>
      </nav>

      <div className="text-xs text-black/50">PT | EN</div>
    </div>
  </header>

  {children}

  <footer className="border-t border-black/10 bg-white">
    <div className="mx-auto max-w-6xl px-6 py-10 text-sm text-black/70">
      <div className="font-semibold text-black">747 Garage</div>
      <div className="mt-2">
        Rua Antonio Viana, 747 — Parque Paulistano, São Paulo
      </div>
      <div className="mt-1">Seg–Sex 08h–16h • WhatsApp +55 11 93010-8649</div>
      <div className="mt-4 text-xs text-black/50">
        Precisão alemã, curadoria brasileira.
      </div>
    </div>
  </footer>
</body>
    </html>
  );
}
